# Copyright (c) 2016 Pete Hanson
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.3.0'

group :development do
  gem 'minitest', '~>5.8.4'
  gem 'minitest-reporters', '~>1.1.8'
  gem 'pry', git: 'https://github.com/pry/pry.git',
             ref: '90d127778f3f4e9581d9dfb5c17851af48867186'
  gem 'pry-power_assert', '~>0.0.2'
  gem 'simplecov', '~>0.11.2'
end
